# Generated by Django 2.1.7 on 2019-03-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('videoid', models.CharField(max_length=100)),
                ('liked', models.BooleanField(default=False)),
            ],
        ),
    ]
