# Generated by Django 2.2.6 on 2019-10-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='videoid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
