FROM python:3.7-slim

# Create a group and user to run our app
ARG APPDIR=/root/ytm

RUN set -ex \
    && RUN_DEPS=" \
    libpcre3 \
    mime-support \
    libgnutls28-dev \
    libcurl4-gnutls-dev \
    " \
    && seq 1 8 | xargs -I{} mkdir -p /usr/share/man/man{} \
    && apt-get update && apt-get install -y --no-install-recommends $RUN_DEPS \
    && rm -rf /var/lib/apt/lists/*


RUN mkdir ${APPDIR}
WORKDIR ${APPDIR}
ADD . ${APPDIR}

RUN set -ex \
    && BUILD_DEPS=" \
    build-essential \
    libpcre3-dev \
    libpq-dev \
    " \
    && apt-get update && apt-get install -y --no-install-recommends $BUILD_DEPS \
    && pip install --no-cache-dir -r ${APPDIR}/requirements.txt \
    \
    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false $BUILD_DEPS \
    && rm -rf /var/lib/apt/lists/*

# uwsgi configuration
ENV UWSGI_WSGI_FILE=ytm/wsgi.py
ENV UWSGI_MASTER=1 UWSGI_HTTP_AUTO_CHUNKED=1 UWSGI_HTTP_KEEPALIVE=1 UWSGI_LAZY_APPS=1 UWSGI_WSGI_ENV_BEHAVIOR=holy
# ENV UWSGI_ROUTE_HOST="^(?!localhost:8000$) break:400"

# ENV PORT 8000
# CMD ["uwsgi", "--http", "$PORT"]
